Refactor code in order to test app using cucumber
Laxynium/XP pull request #10
Opened 2021-05-12 19:08 UTC by Laxynium

* Add advertisement facade with configuration
 * Use facade in main and cucumber tests
 * Use input and output streams as parameters

2021-05-17 15:53 UTC, patrykbober requested changes

2021-05-17 15:55 UTC, Laxynium commented on src/test/java/features/ShowAvailableAds.java
> +    private final File file = new File("testData");
Z tym @TempDir jest taki problem, że to nie działa z tym Cucumberem :(.

2021-05-17 16:21 UTC, patrykbober commented on src/test/java/features/ShowAvailableAds.java
> +    private final File file = new File("testData");
ok faktycznie, zostawmy w takim razie tak jak jest

2021-05-17 20:44 UTC, patrykbober approved these changes

2021-05-24 21:16 UTC, Adrjanjan approved these changes

2021-05-24 21:45 UTC, merged